/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author euced
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        try {
            adminU.cargarArchivo();
            listaUsuarios = adminU.getListaUsuarios();
            for (Usuario u : listaUsuarios) {
                if (u instanceof UsuarioAdmin) {
                    listaAdmin.add((UsuarioAdmin)u);
                }else{
                    listaNormal.add((UsuarioNormal)u);
                    for (Publicacion p : ((UsuarioNormal)u).getListaPublicaciones()) {
                        listaPublicaciones.add(p);
                    }
                    
                }
            }
        } catch (Exception e) {
            System.out.println("ocurrio un error");

        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_signup = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_usuario = new javax.swing.JTextField();
        tf_contrasenina = new javax.swing.JTextField();
        tf_foto = new javax.swing.JLabel();
        js_fechaN = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        rb_admin = new javax.swing.JRadioButton();
        rb_normal = new javax.swing.JRadioButton();
        btn_registrar = new javax.swing.JButton();
        btn_seleccionarF = new javax.swing.JButton();
        jd_login = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_usuarioLI = new javax.swing.JTextField();
        tf_passwordLI = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        jd_homeAdmin = new javax.swing.JDialog();
        tab_admin = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_usuarios = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_publicaciones = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jd_homeNormal = new javax.swing.JDialog();
        tab_normal = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_publicacion = new javax.swing.JTextArea();
        btn_hacerPubli = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_publiNormal = new javax.swing.JList<>();
        tf_filtro1 = new javax.swing.JTextField();
        btn_filtrarPublicaciones1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_usuariosN = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jt_amigos = new javax.swing.JTree();
        jScrollPane10 = new javax.swing.JScrollPane();
        jt_solicitudes = new javax.swing.JTree();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_email = new javax.swing.JLabel();
        jl_fecha = new javax.swing.JLabel();
        jl_usuario = new javax.swing.JLabel();
        jl_password = new javax.swing.JLabel();
        jl_foto = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_publiNormal1 = new javax.swing.JList<>();
        btn_filtrarPublicaciones = new javax.swing.JButton();
        tf_filtro = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jt_publicaciones = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menu_popResponder = new javax.swing.JPopupMenu();
        Responder = new javax.swing.JMenuItem();
        jd_responder = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_respuesta = new javax.swing.JTextArea();
        btn_responder = new javax.swing.JButton();
        jd_modificar = new javax.swing.JDialog();
        jl_foto1 = new javax.swing.JLabel();
        btn_seleccionarF1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        tf_email1 = new javax.swing.JTextField();
        js_fechaN1 = new javax.swing.JSpinner();
        tf_usuario1 = new javax.swing.JTextField();
        tf_contrasenina1 = new javax.swing.JTextField();
        btn_modi = new javax.swing.JButton();
        menu_pop2 = new javax.swing.JPopupMenu();
        jmi_eliminar = new javax.swing.JMenuItem();
        menu_popSoli = new javax.swing.JPopupMenu();
        jmi_aceptar = new javax.swing.JMenuItem();
        jmi_rechazar = new javax.swing.JMenuItem();
        menu_popES = new javax.swing.JPopupMenu();
        jmi_enviarSoli = new javax.swing.JMenuItem();
        menu_popAmigos = new javax.swing.JPopupMenu();
        jmi_eliminarAmigo = new javax.swing.JMenuItem();
        menu_popB = new javax.swing.JPopupMenu();
        jmi_bloquear = new javax.swing.JMenuItem();
        menu_popBP = new javax.swing.JPopupMenu();
        jmi_bloquear1 = new javax.swing.JMenuItem();
        btn_login = new javax.swing.JButton();
        btn_signup = new javax.swing.JButton();

        jLabel1.setText("SignUp");

        jLabel2.setText("Nombre");

        jLabel3.setText("Email");

        jLabel4.setText("Fecha Nacimiento");

        jLabel5.setText("Usuario");

        jLabel6.setText("Password");

        jLabel7.setText("Foto");

        js_fechaN.setModel(new javax.swing.SpinnerDateModel());

        jLabel9.setText("Tipo Usuario");

        rb_admin.setText("Administrador");
        rb_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_adminActionPerformed(evt);
            }
        });

        rb_normal.setText("Normal");

        btn_registrar.setText("SignUp");
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarMouseClicked(evt);
            }
        });

        btn_seleccionarF.setText("SeleccionarFoto");
        btn_seleccionarF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seleccionarFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_signupLayout = new javax.swing.GroupLayout(jd_signup.getContentPane());
        jd_signup.getContentPane().setLayout(jd_signupLayout);
        jd_signupLayout.setHorizontalGroup(
            jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signupLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_seleccionarF)
                    .addGroup(jd_signupLayout.createSequentialGroup()
                        .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(84, 84, 84)
                        .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jd_signupLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rb_normal)
                                    .addComponent(tf_contrasenina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(tf_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(js_fechaN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_foto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jd_signupLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_admin)
                            .addComponent(btn_registrar)))
                    .addComponent(jLabel9))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jd_signupLayout.setVerticalGroup(
            jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(js_fechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_contrasenina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btn_seleccionarF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_admin)
                    .addComponent(rb_normal))
                .addGap(18, 18, 18)
                .addComponent(btn_registrar)
                .addGap(13, 13, 13))
        );

        jLabel10.setText("LogIn");

        jLabel11.setText("Usuario");

        jLabel12.setText("Contraseña");

        btn_ingresar.setText("LogIn");
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel10))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_passwordLI, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(tf_usuarioLI))))
                .addGap(107, 107, 107))
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btn_ingresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addGap(39, 39, 39)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_usuarioLI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_passwordLI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btn_ingresar)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tab_admin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_adminStateChanged(evt);
            }
        });

        jl_usuarios.setModel(new DefaultListModel());
        jl_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_usuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_usuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_admin.addTab("Usuarios", jPanel1);

        jl_publicaciones.setModel(new DefaultListModel());
        jl_publicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_publicacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_publicaciones);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        tab_admin.addTab("Publicaciones", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        tab_admin.addTab("Reducir Archivo", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        tab_admin.addTab("Ver Archivo", jPanel4);

        jMenu3.setText("Guardar");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Salir");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        jMenu5.setText("About");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu5);

        jd_homeAdmin.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jd_homeAdminLayout = new javax.swing.GroupLayout(jd_homeAdmin.getContentPane());
        jd_homeAdmin.getContentPane().setLayout(jd_homeAdminLayout);
        jd_homeAdminLayout.setHorizontalGroup(
            jd_homeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_admin)
        );
        jd_homeAdminLayout.setVerticalGroup(
            jd_homeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_homeAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_admin))
        );

        tab_normal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_normalStateChanged(evt);
            }
        });

        ta_publicacion.setColumns(20);
        ta_publicacion.setRows(5);
        jScrollPane3.setViewportView(ta_publicacion);

        btn_hacerPubli.setText("Hacer Publicacion");
        btn_hacerPubli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hacerPubliMouseClicked(evt);
            }
        });

        jl_publiNormal.setModel(new DefaultListModel());
        jl_publiNormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_publiNormalMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jl_publiNormal);

        btn_filtrarPublicaciones1.setText("Filtrar");
        btn_filtrarPublicaciones1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_filtrarPublicaciones1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_hacerPubli)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_filtrarPublicaciones1)
                    .addComponent(tf_filtro1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_filtro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_filtrarPublicaciones1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_hacerPubli)
                .addGap(24, 24, 24))
        );

        tab_normal.addTab("Publicar", jPanel5);

        jl_usuariosN.setModel(new DefaultListModel());
        jl_usuariosN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_usuariosNMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jl_usuariosN);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Amigos");
        jt_amigos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_amigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_amigosMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jt_amigos);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Solicitudes");
        jt_solicitudes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_solicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_solicitudesMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jt_solicitudes);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tab_normal.addTab("Usuarios", jPanel6);

        jLabel8.setText("Nombre");

        jLabel13.setText("Email");

        jLabel14.setText("Fecha Nacimiento");

        jLabel15.setText("Usuario");

        jLabel16.setText("Password");

        jLabel17.setText("Foto");

        jl_nombre.setText("jLabel18");

        jl_email.setText("jLabel18");

        jl_fecha.setText("jLabel18");

        jl_usuario.setText("jLabel18");

        jl_password.setText("jLabel18");

        btn_modificar.setText("Modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGap(215, 215, 215)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_email)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jl_nombre)
                                .addGap(128, 128, 128)
                                .addComponent(btn_modificar))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(168, 168, 168)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_foto)
                            .addComponent(jl_password)
                            .addComponent(jl_usuario)
                            .addComponent(jl_fecha))))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jl_nombre)
                    .addComponent(btn_modificar))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jl_email)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jl_fecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jl_usuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jl_password))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jl_foto))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        tab_normal.addTab("Informacion Personal", jPanel7);

        jl_publiNormal1.setModel(new DefaultListModel());
        jl_publiNormal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_publiNormal1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jl_publiNormal1);

        btn_filtrarPublicaciones.setText("Filtrar");
        btn_filtrarPublicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_filtrarPublicacionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_filtrarPublicaciones)
                    .addComponent(tf_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(tf_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_filtrarPublicaciones)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        tab_normal.addTab("Publicaciones", jPanel8);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mis Publicaciones");
        jt_publicaciones.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_publicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_publicacionesMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jt_publicaciones);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tab_normal.addTab("Mis Publicaciones", jPanel9);

        jMenu1.setText("Salir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                jMenu2MenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jd_homeNormal.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_homeNormalLayout = new javax.swing.GroupLayout(jd_homeNormal.getContentPane());
        jd_homeNormal.getContentPane().setLayout(jd_homeNormalLayout);
        jd_homeNormalLayout.setHorizontalGroup(
            jd_homeNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_normal)
        );
        jd_homeNormalLayout.setVerticalGroup(
            jd_homeNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_homeNormalLayout.createSequentialGroup()
                .addComponent(tab_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Responder.setText("Responder");
        Responder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponderActionPerformed(evt);
            }
        });
        menu_popResponder.add(Responder);

        ta_respuesta.setColumns(20);
        ta_respuesta.setRows(5);
        jScrollPane5.setViewportView(ta_respuesta);

        btn_responder.setText("Rsponder");
        btn_responder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_responderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_responderLayout = new javax.swing.GroupLayout(jd_responder.getContentPane());
        jd_responder.getContentPane().setLayout(jd_responderLayout);
        jd_responderLayout.setHorizontalGroup(
            jd_responderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_responderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_responderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_responder)
                .addGap(62, 62, 62))
        );
        jd_responderLayout.setVerticalGroup(
            jd_responderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_responderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_responder)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btn_seleccionarF1.setText("SeleccionarFoto");
        btn_seleccionarF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seleccionarF1MouseClicked(evt);
            }
        });

        jLabel18.setText("Foto");

        jLabel19.setText("Password");

        jLabel20.setText("Usuario");

        jLabel21.setText("Fecha Nacimiento");

        jLabel22.setText("Email");

        jLabel23.setText("Nombre");

        js_fechaN1.setModel(new javax.swing.SpinnerDateModel());

        btn_modi.setText("Modificar");
        btn_modi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarLayout = new javax.swing.GroupLayout(jd_modificar.getContentPane());
        jd_modificar.getContentPane().setLayout(jd_modificarLayout);
        jd_modificarLayout.setHorizontalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btn_seleccionarF1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(btn_modi)
                .addGap(99, 99, 99))
            .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_modificarLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jLabel21)
                        .addComponent(jLabel20)
                        .addComponent(jLabel19)
                        .addComponent(jLabel18))
                    .addGap(94, 94, 94)
                    .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_contrasenina1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(tf_nombre1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_usuario1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(tf_email1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(js_fechaN1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jl_foto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        jd_modificarLayout.setVerticalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(btn_seleccionarF1)
                .addGap(11, 11, 11)
                .addComponent(btn_modi)
                .addContainerGap())
            .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_modificarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(tf_email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(js_fechaN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(tf_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(tf_contrasenina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jl_foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        menu_pop2.add(jmi_eliminar);

        jmi_aceptar.setText("Aceptar");
        jmi_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_aceptarActionPerformed(evt);
            }
        });
        menu_popSoli.add(jmi_aceptar);

        jmi_rechazar.setText("Rechazar");
        jmi_rechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_rechazarActionPerformed(evt);
            }
        });
        menu_popSoli.add(jmi_rechazar);

        jmi_enviarSoli.setText("Enviar Solicitud");
        jmi_enviarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_enviarSoliActionPerformed(evt);
            }
        });
        menu_popES.add(jmi_enviarSoli);

        jmi_eliminarAmigo.setText("Eliminar");
        jmi_eliminarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarAmigoActionPerformed(evt);
            }
        });
        menu_popAmigos.add(jmi_eliminarAmigo);

        jmi_bloquear.setText("Bloquear");
        jmi_bloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_bloquearActionPerformed(evt);
            }
        });
        menu_popB.add(jmi_bloquear);

        jmi_bloquear1.setText("Bloquear");
        jmi_bloquear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_bloquear1ActionPerformed(evt);
            }
        });
        menu_popBP.add(jmi_bloquear1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btn_login.setText("LogIn");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_signup.setText("SignUp");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(btn_signup)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login)
                    .addComponent(btn_signup))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_adminActionPerformed

    private void btn_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseClicked
        // TODO add your handling code here:
        String nombre, email, usuario, password;
        Date fechaNacimiento;
        if (rb_admin.isSelected()) {
            UsuarioAdmin ua = new UsuarioAdmin(tf_nombre.getText(), tf_email.getText(), (Date) js_fechaN.getValue(),
                    tf_usuario.getText(), tf_contrasenina.getText(), tf_foto.getIcon());
            listaAdmin.add(ua);
            listaUsuarios.add(ua);
            JOptionPane.showMessageDialog(this, "Se ha ingresado exitosamente");
        } else if (rb_normal.isSelected()) {
            UsuarioNormal ua = new UsuarioNormal(tf_nombre.getText(), tf_email.getText(), (Date) js_fechaN.getValue(),
                    tf_usuario.getText(), tf_contrasenina.getText(), tf_foto.getIcon());
            listaNormal.add(ua);
            listaUsuarios.add(ua);
            JOptionPane.showMessageDialog(this, "Se ha ingresado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "No seleccionó tipo de usuario");
        }

        tf_nombre.setText("");
        tf_email.setText("");
        tf_usuario.setText("");
        tf_contrasenina.setText("");
        js_fechaN.setValue(new Date());
        tf_foto.setText(" ");
        jd_signup.setVisible(false);


    }//GEN-LAST:event_btn_registrarMouseClicked

    private void btn_seleccionarFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seleccionarFMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(100, 100, 0);
            this.tf_foto.setIcon(new ImageIcon(img));

        }
    }//GEN-LAST:event_btn_seleccionarFMouseClicked

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        this.jd_signup.setModal(true);
        this.jd_signup.pack();
        this.jd_signup.setLocationRelativeTo(this);
        this.jd_signup.setVisible(true);
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        this.jd_login.setModal(true);
        this.jd_login.pack();
        this.jd_login.setLocationRelativeTo(this);
        this.jd_login.setVisible(true);
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseClicked
        // TODO add your handling code here:
        boolean flag = false;
        for (Usuario un : listaUsuarios) {
            if (un.getUsuario().equals(tf_usuarioLI.getText()) && un.getPassword().equals(tf_passwordLI.getText())) {

                flag = true;
                JOptionPane.showMessageDialog(this, "Ha ingresado exitosamente");
                if (un instanceof UsuarioAdmin) {
                    admin_loggeado = (UsuarioAdmin) un;
                    this.jd_homeAdmin.setModal(true);
                    this.jd_homeAdmin.pack();
                    this.jd_homeAdmin.setLocationRelativeTo(this);
                    this.jd_homeAdmin.setVisible(true);
                    tab_admin.setSelectedIndex(0);
                } else if (un instanceof UsuarioNormal) {
                    usuario_loggeado = (UsuarioNormal) un;
                    this.jd_homeNormal.setModal(true);
                    this.jd_homeNormal.pack();
                    this.jd_homeNormal.setLocationRelativeTo(this);
                    this.jd_homeNormal.setVisible(true);
                }
            }
        }
        tf_usuarioLI.setText("");
        tf_passwordLI.setText("");
        jd_login.setVisible(false);
        if (flag) {

        } else {
            JOptionPane.showMessageDialog(this, "No coiciden los campos");
        }
    }//GEN-LAST:event_btn_ingresarMouseClicked

    private void tab_adminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab_adminStateChanged
        // TODO add your handling code here:
        if (tab_admin.getSelectedIndex() == 0) {
            try {
                DefaultListModel modelo = (DefaultListModel) jl_usuarios.getModel();
                modelo.clear();
                for (UsuarioNormal un : listaNormal) {
                    if (un instanceof UsuarioNormal) {
                        modelo.addElement(un);

                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println(e.getMessage());
            }

        } else if (tab_admin.getSelectedIndex() == 1) {
            try {
                DefaultListModel modelo = (DefaultListModel) jl_publicaciones.getModel();
                modelo.clear();
                for (Publicacion p : listaPublicaciones) {
                    modelo.addElement(p);

                }
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_tab_adminStateChanged

    private void btn_hacerPubliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hacerPubliMouseClicked
        // TODO add your handling code here:
        if (listaPublicaciones.isEmpty()) {

            Problema prob = new Problema("Abierto", 5, 0, ta_publicacion.getText(), usuario_loggeado, "privado", new Date());
            listaPublicaciones.add(prob);
            usuario_loggeado.getListaPublicaciones().add(prob);
        } else {
            int fin = listaPublicaciones.size();
            int p = listaPublicaciones.get(fin - 1).getId();
            Problema prob = new Problema("Abierto", 5, p + 1, ta_publicacion.getText(), usuario_loggeado, "privado", new Date());
            listaPublicaciones.add(prob);
            usuario_loggeado.getListaPublicaciones().add(prob);
        }
        DefaultListModel modelo = (DefaultListModel) jl_publiNormal.getModel();
        modelo.clear();
        for (Publicacion p : listaPublicaciones) {
            modelo.addElement(p);
        }
        ta_publicacion.setText("");
    }//GEN-LAST:event_btn_hacerPubliMouseClicked

    private void tab_normalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab_normalStateChanged
        // TODO add your handling code here:
        System.out.println(tab_normal.getSelectedIndex());
        if (tab_normal.getSelectedIndex() == 0) {
            DefaultListModel modelo = (DefaultListModel) jl_publiNormal.getModel();
            modelo.clear();
            for (Publicacion p : listaPublicaciones) {
                modelo.addElement(p);
            }
        } else if (tab_normal.getSelectedIndex() == 2) {
            System.out.println(usuario_loggeado.getNombre());
            jl_nombre.setText(usuario_loggeado.getNombre());
            jl_email.setText(usuario_loggeado.getEmail());
            jl_fecha.setText(usuario_loggeado.getFechaNacimiento().toString());
            jl_usuario.setText(usuario_loggeado.getUsuario());
            jl_password.setText(usuario_loggeado.getPassword());
            jl_foto.setIcon(usuario_loggeado.getFotografia());

        } else if (tab_normal.getSelectedIndex() == 3) {
            DefaultListModel modelo = (DefaultListModel) jl_publiNormal1.getModel();
            modelo.clear();
            for (Publicacion p : listaPublicaciones) {
                modelo.addElement(p);
            }
        } else if (tab_normal.getSelectedIndex() == 4) {
            DefaultTreeModel m = (DefaultTreeModel) jt_publicaciones.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            for (Publicacion publi : usuario_loggeado.getListaPublicaciones()) {
                DefaultMutableTreeNode nodo_publi;
                nodo_publi = new DefaultMutableTreeNode(publi);
                raiz.add(nodo_publi);
            }
            m.reload();
        } else if (tab_normal.getSelectedIndex() == 1) {
            DefaultListModel modelo = (DefaultListModel) jl_usuariosN.getModel();

            for (UsuarioNormal p : listaNormal) {
                if (p.equals(usuario_loggeado)) {
                } else {
                    modelo.addElement(p);
                }
            }
            for (UsuarioNormal un : usuario_loggeado.getListaSolicitudes()) {
                DefaultTreeModel m = (DefaultTreeModel) jt_solicitudes.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                modelo.clear();
                DefaultMutableTreeNode nodo_publi;
                nodo_publi = new DefaultMutableTreeNode(un);
                raiz.add(nodo_publi);
                m.reload();
            }
            for (UsuarioNormal amigo : usuario_loggeado.getListaAmigos()) {
                DefaultTreeModel m = (DefaultTreeModel) jt_amigos.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                modelo.clear();
                DefaultMutableTreeNode nodo_publi;
                nodo_publi = new DefaultMutableTreeNode(amigo);
                raiz.add(nodo_publi);
                m.reload();
            }
        }

    }//GEN-LAST:event_tab_normalStateChanged

    private void ResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponderActionPerformed
        // TODO add your handling code here:
        this.jd_responder.setModal(true);
        this.jd_responder.pack();
        this.jd_responder.setLocationRelativeTo(this);
        jd_responder.setVisible(true);

    }//GEN-LAST:event_ResponderActionPerformed

    private void btn_responderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_responderMouseClicked
        // TODO add your handling code here:
        int fin = listaPublicaciones.size();
        int p = listaPublicaciones.get(fin - 1).getId();
        Respuesta prob = new Respuesta(2.2, p + 1, ta_respuesta.getText(), usuario_loggeado, "privado", new Date());
        problema_seleccionado.getRespuestas().add(prob);
        ta_respuesta.setText("");
        jd_responder.setVisible(false);
    }//GEN-LAST:event_btn_responderMouseClicked

    private void jl_publiNormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_publiNormalMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jl_publiNormal.getSelectedIndex();
            if (row >= 0) {
                DefaultListModel modelo = (DefaultListModel) jl_publiNormal.getModel();
                problema_seleccionado = (Problema) modelo.getElementAt(jl_publiNormal.getSelectedIndex());
                menu_popResponder.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_publiNormalMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_seleccionarF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seleccionarF1MouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(100, 100, 0);
            this.tf_foto.setIcon(new ImageIcon(img));

        }
    }//GEN-LAST:event_btn_seleccionarF1MouseClicked

    private void btn_modiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modiMouseClicked
        // TODO add your handling code here:
        usuario_loggeado.setNombre(tf_nombre1.getText());
        usuario_loggeado.setEmail(tf_email1.getText());
        usuario_loggeado.setFechaNacimiento((Date) js_fechaN1.getValue());
        usuario_loggeado.setUsuario(tf_usuario1.getText());
        usuario_loggeado.setPassword(tf_contrasenina1.getText());
        usuario_loggeado.setFotografia(jl_foto1.getIcon());

        tf_nombre1.setText("");
        tf_email1.setText("");
        js_fechaN1.setValue(new Date());
        tf_usuario1.setText("");
        tf_contrasenina1.setText("");
        jl_foto1.setIcon(null);

        jl_nombre.setText(usuario_loggeado.getNombre());
        jl_email.setText(usuario_loggeado.getEmail());
        jl_fecha.setText(usuario_loggeado.getFechaNacimiento().toString());
        jl_usuario.setText(usuario_loggeado.getUsuario());
        jl_password.setText(usuario_loggeado.getPassword());
        jl_foto.setIcon(usuario_loggeado.getFotografia());

    }//GEN-LAST:event_btn_modiMouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        this.jd_modificar.setModal(true);
        this.jd_modificar.pack();
        this.jd_modificar.setLocationRelativeTo(this);
        jd_modificar.setVisible(true);
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void jl_publiNormal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_publiNormal1MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jl_publiNormal1.getSelectedIndex();
            if (row >= 0) {
                DefaultListModel modelo = (DefaultListModel) jl_publiNormal1.getModel();
                problema_seleccionado = (Problema) modelo.getElementAt(jl_publiNormal1.getSelectedIndex());
                menu_popResponder.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }

    }//GEN-LAST:event_jl_publiNormal1MouseClicked

    private void jt_publicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_publicacionesMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_publicaciones.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_publicaciones.setSelectionRow(row);
            Object v1 = jt_publicaciones.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Publicacion) {
                publicacion_seleccionada = (Publicacion) nodo_seleccionado.getUserObject();
                menu_pop2.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_jt_publicacionesMouseClicked

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Seguro de Eliminar?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m = (DefaultTreeModel) jt_publicaciones.getModel();
            m.removeNodeFromParent(nodo_seleccionado);
            m.reload();
            usuario_loggeado.getListaPublicaciones().remove(publicacion_seleccionada);
            listaPublicaciones.remove(publicacion_seleccionada);
        }
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        adminU.setListaUsuarios(listaUsuarios);
        adminU.escribirArchivo();
        System.exit(0);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MenuCanceled

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(jd_homeNormal, "Este es mi bonito programa");
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        adminU.setListaUsuarios(listaUsuarios);
        adminU.escribirArchivo();
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jt_solicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_solicitudesMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_solicitudes.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_solicitudes.setSelectionRow(row);
            Object v1 = jt_solicitudes.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof UsuarioNormal) {
                usuario_seleccionado = (UsuarioNormal) nodo_seleccionado.getUserObject();
                menu_popSoli.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_jt_solicitudesMouseClicked

    private void jmi_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_aceptarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_solicitudes.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
        usuario_loggeado.getListaAmigos().add(usuario_seleccionado);
        usuario_loggeado.getListaSolicitudes().remove(usuario_seleccionado);
        for (UsuarioNormal amigo : usuario_loggeado.getListaAmigos()) {
            DefaultTreeModel ma = (DefaultTreeModel) jt_amigos.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) ma.getRoot();
            DefaultMutableTreeNode nodo_publi;
            nodo_publi = new DefaultMutableTreeNode(amigo);
            raiz.add(nodo_publi);
            ma.reload();
        }


    }//GEN-LAST:event_jmi_aceptarActionPerformed

    private void jl_usuariosNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_usuariosNMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jl_usuariosN.getSelectedIndex();
            if (row >= 0) {
                DefaultListModel modelo = (DefaultListModel) jl_usuariosN.getModel();
                usuario_seleccionado = (UsuarioNormal) modelo.getElementAt(jl_usuariosN.getSelectedIndex());
                menu_popES.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_usuariosNMouseClicked

    private void jmi_enviarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_enviarSoliActionPerformed
        // TODO add your handling code here:
        usuario_seleccionado.getListaSolicitudes().add(usuario_loggeado);

    }//GEN-LAST:event_jmi_enviarSoliActionPerformed

    private void jmi_rechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_rechazarActionPerformed
        // TODO add your handling code here:'
        usuario_loggeado.getListaSolicitudes().remove(usuario_seleccionado);
        DefaultTreeModel m = (DefaultTreeModel) jt_solicitudes.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_jmi_rechazarActionPerformed

    private void jt_amigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_amigosMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_amigos.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_amigos.setSelectionRow(row);
            Object v1 = jt_amigos.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof UsuarioNormal) {
                usuario_seleccionado = (UsuarioNormal) nodo_seleccionado.getUserObject();
                menu_popAmigos.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_jt_amigosMouseClicked

    private void jmi_eliminarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarAmigoActionPerformed
        // TODO add your handling code here:
        usuario_loggeado.getListaAmigos().remove(usuario_seleccionado);
        DefaultTreeModel m = (DefaultTreeModel) jt_solicitudes.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_jmi_eliminarAmigoActionPerformed

    private void btn_filtrarPublicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filtrarPublicacionesMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_publiNormal1.getModel();
        modelo.clear();
        for (Publicacion p : listaPublicaciones) {
            if (p.getMensaje().contains(tf_filtro.getText())) {
                modelo.addElement(p);
            }

        }
    }//GEN-LAST:event_btn_filtrarPublicacionesMouseClicked

    private void btn_filtrarPublicaciones1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filtrarPublicaciones1MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_publiNormal.getModel();
        modelo.clear();
        for (Publicacion p : listaPublicaciones) {
            if (p.getMensaje().contains(tf_filtro.getText())) {
                modelo.addElement(p);
            }

        }
    }//GEN-LAST:event_btn_filtrarPublicaciones1MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(jd_homeAdmin, "Este es mi hermoso programa");
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo Binario", "cbm");
        jfc.addChoosableFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);
        FileWriter fw = null;
        BufferedWriter br = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals("Archivo Binario")) {
                    fichero = new File(jfc.getSelectedFile().getPath() + ".cbm");

                } else {
                    fichero = jfc.getSelectedFile();
                }
                adminU.setListaUsuarios(listaUsuarios);
                adminU.setArchivo(fichero);
                adminU.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                br.close();
                fw.close();
            } catch (IOException e) {
            }
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        adminU.setListaUsuarios(listaUsuarios);
        adminU.escribirArchivo();
    }//GEN-LAST:event_formWindowClosed

    private void jl_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_usuariosMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jl_usuarios.getSelectedIndex();
            if (row >= 0) {
                DefaultListModel modelo = (DefaultListModel) jl_usuarios.getModel();
                usuario_seleccionado = (UsuarioNormal) modelo.getElementAt(jl_usuarios.getSelectedIndex());
                menu_popB.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
        
    }//GEN-LAST:event_jl_usuariosMouseClicked

    private void jmi_bloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_bloquearActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_usuarios.getModel();
        listaUsuarios.remove(usuario_seleccionado);
    }//GEN-LAST:event_jmi_bloquearActionPerformed

    private void jl_publicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_publicacionesMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jl_publicaciones.getSelectedIndex();
            if (row >= 0) {
                DefaultListModel modelo = (DefaultListModel) jl_publicaciones.getModel();
                publicacion_seleccionada = (Publicacion) modelo.getElementAt(jl_publicaciones.getSelectedIndex());
                menu_popBP.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_publicacionesMouseClicked

    private void jmi_bloquear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_bloquear1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_publicaciones.getModel();
        listaPublicaciones.remove(publicacion_seleccionada);
    }//GEN-LAST:event_jmi_bloquear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Responder;
    private javax.swing.JButton btn_filtrarPublicaciones;
    private javax.swing.JButton btn_filtrarPublicaciones1;
    private javax.swing.JButton btn_hacerPubli;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_modi;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_responder;
    private javax.swing.JButton btn_seleccionarF;
    private javax.swing.JButton btn_seleccionarF1;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JDialog jd_homeAdmin;
    private javax.swing.JDialog jd_homeNormal;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_modificar;
    private javax.swing.JDialog jd_responder;
    private javax.swing.JDialog jd_signup;
    private javax.swing.JLabel jl_email;
    private javax.swing.JLabel jl_fecha;
    private javax.swing.JLabel jl_foto;
    private javax.swing.JLabel jl_foto1;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_password;
    private javax.swing.JList<String> jl_publiNormal;
    private javax.swing.JList<String> jl_publiNormal1;
    private javax.swing.JList<String> jl_publicaciones;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JList<String> jl_usuarios;
    private javax.swing.JList<String> jl_usuariosN;
    private javax.swing.JMenuItem jmi_aceptar;
    private javax.swing.JMenuItem jmi_bloquear;
    private javax.swing.JMenuItem jmi_bloquear1;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_eliminarAmigo;
    private javax.swing.JMenuItem jmi_enviarSoli;
    private javax.swing.JMenuItem jmi_rechazar;
    private javax.swing.JSpinner js_fechaN;
    private javax.swing.JSpinner js_fechaN1;
    private javax.swing.JTree jt_amigos;
    private javax.swing.JTree jt_publicaciones;
    private javax.swing.JTree jt_solicitudes;
    private javax.swing.JPopupMenu menu_pop2;
    private javax.swing.JPopupMenu menu_popAmigos;
    private javax.swing.JPopupMenu menu_popB;
    private javax.swing.JPopupMenu menu_popBP;
    private javax.swing.JPopupMenu menu_popES;
    private javax.swing.JPopupMenu menu_popResponder;
    private javax.swing.JPopupMenu menu_popSoli;
    private javax.swing.JRadioButton rb_admin;
    private javax.swing.JRadioButton rb_normal;
    private javax.swing.JTextArea ta_publicacion;
    private javax.swing.JTextArea ta_respuesta;
    private javax.swing.JTabbedPane tab_admin;
    private javax.swing.JTabbedPane tab_normal;
    private javax.swing.JTextField tf_contrasenina;
    private javax.swing.JTextField tf_contrasenina1;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_email1;
    private javax.swing.JTextField tf_filtro;
    private javax.swing.JTextField tf_filtro1;
    private javax.swing.JLabel tf_foto;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_passwordLI;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuario1;
    private javax.swing.JTextField tf_usuarioLI;
    // End of variables declaration//GEN-END:variables

    ArrayList<UsuarioAdmin> listaAdmin = new ArrayList();
    UsuarioNormal usuario_loggeado, usuario_seleccionado;
    UsuarioAdmin admin_loggeado;
    ArrayList<UsuarioNormal> listaNormal = new ArrayList();
    ArrayList<Usuario> listaUsuarios = new ArrayList();
    ArrayList<Publicacion> listaPublicaciones = new ArrayList();
    Problema problema_seleccionado;
    DefaultMutableTreeNode nodo_seleccionado;
    Publicacion publicacion_seleccionada;
    AdminUsuarios adminU = new AdminUsuarios("./usuarios.cbm");
}
